-- Baseline migration: the target database already contains the schema
-- represented by drizzle/meta/0018_snapshot.json (exercises external-reference
-- columns/indexes, foodCatalog classification columns, and the renamed
-- meals_user_status_occurredAt_idx index were already applied out-of-band).
-- This no-op aligns Drizzle's migration history without replaying DDL for
-- existing tables. See drizzle/0016_warm_the_executioner.sql for precedent.