CREATE TABLE IF NOT EXISTS `billingUsageEvents` (
  `id` varchar(64) NOT NULL,
  `idempotencyKey` varchar(191) NOT NULL,
  `beneficiaryUserId` int NOT NULL,
  `patientUserId` int NULL,
  `sponsorUserId` int NULL,
  `payerUserId` int NOT NULL,
  `subscriptionId` varchar(64) NULL,
  `productCode` varchar(120) NULL,
  `versionCode` varchar(191) NULL,
  `billingCycle` varchar(32) NULL,
  `accessSource` varchar(64) NOT NULL,
  `operation` varchar(120) NOT NULL,
  `channel` varchar(64) NOT NULL,
  `provider` varchar(64) NULL,
  `model` varchar(191) NULL,
  `unitType` varchar(64) NOT NULL,
  `unitCount` bigint NOT NULL DEFAULT 1,
  `estimatedCostMicros` bigint NULL,
  `effectiveCostMicros` bigint NULL,
  `currency` varchar(3) NULL,
  `eventState` varchar(32) NOT NULL,
  `attemptRole` varchar(32) NOT NULL DEFAULT 'primary',
  `retryRootKey` varchar(191) NULL,
  `correlationId` varchar(191) NOT NULL,
  `environment` varchar(32) NOT NULL,
  `ruleVersion` varchar(64) NOT NULL,
  `metadataJson` json NULL,
  `occurredAt` timestamp NOT NULL,
  `competenceDate` date NOT NULL,
  `legalHold` boolean NOT NULL DEFAULT false,
  `invalidatedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billingUsageEvents_idempotency_uq` (`idempotencyKey`),
  KEY `billingUsageEvents_beneficiary_occurred_idx` (`beneficiaryUserId`, `occurredAt`),
  KEY `billingUsageEvents_sponsor_occurred_idx` (`sponsorUserId`, `occurredAt`),
  KEY `billingUsageEvents_subscription_occurred_idx` (`subscriptionId`, `occurredAt`),
  KEY `billingUsageEvents_operation_occurred_idx` (`operation`, `occurredAt`),
  KEY `billingUsageEvents_competence_idx` (`competenceDate`)
);

CREATE TABLE IF NOT EXISTS `billingUsageDailyAggregates` (
  `aggregateKey` varchar(191) NOT NULL,
  `usageDate` date NOT NULL,
  `beneficiaryUserId` int NOT NULL,
  `sponsorUserId` int NULL,
  `payerUserId` int NOT NULL,
  `subscriptionId` varchar(64) NULL,
  `productCode` varchar(120) NULL,
  `versionCode` varchar(191) NULL,
  `billingCycle` varchar(32) NULL,
  `accessSource` varchar(64) NOT NULL,
  `operation` varchar(120) NOT NULL,
  `channel` varchar(64) NOT NULL,
  `provider` varchar(64) NULL,
  `model` varchar(191) NULL,
  `currency` varchar(3) NULL,
  `eventCount` bigint NOT NULL DEFAULT 0,
  `unitCount` bigint NOT NULL DEFAULT 0,
  `successCount` bigint NOT NULL DEFAULT 0,
  `failureCount` bigint NOT NULL DEFAULT 0,
  `retryCount` bigint NOT NULL DEFAULT 0,
  `estimatedCostMicros` bigint NOT NULL DEFAULT 0,
  `effectiveCostMicros` bigint NOT NULL DEFAULT 0,
  `unpricedCount` bigint NOT NULL DEFAULT 0,
  `ruleVersion` varchar(64) NOT NULL,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`aggregateKey`),
  KEY `billingUsageDailyAggregates_date_idx` (`usageDate`),
  KEY `billingUsageDailyAggregates_payer_date_idx` (`payerUserId`, `usageDate`),
  KEY `billingUsageDailyAggregates_version_date_idx` (`versionCode`, `usageDate`)
);

CREATE TABLE IF NOT EXISTS `billingEconomicFacts` (
  `id` varchar(64) NOT NULL,
  `idempotencyKey` varchar(191) NOT NULL,
  `subscriptionId` varchar(64) NULL,
  `payerUserId` int NOT NULL,
  `productCode` varchar(120) NULL,
  `versionCode` varchar(191) NULL,
  `billingCycle` varchar(32) NULL,
  `factType` varchar(64) NOT NULL,
  `amountMinor` bigint NOT NULL,
  `currency` varchar(3) NOT NULL,
  `valueKind` varchar(16) NOT NULL,
  `competenceStart` date NOT NULL,
  `competenceEnd` date NOT NULL,
  `effectiveAt` timestamp NOT NULL,
  `ruleVersion` varchar(64) NOT NULL,
  `reason` varchar(255) NULL,
  `actorUserId` int NULL,
  `correlationId` varchar(191) NOT NULL,
  `metadataJson` json NULL,
  `invalidatedAt` timestamp NULL,
  `legalHold` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billingEconomicFacts_idempotency_uq` (`idempotencyKey`),
  KEY `billingEconomicFacts_subscription_competence_idx` (`subscriptionId`, `competenceStart`),
  KEY `billingEconomicFacts_payer_competence_idx` (`payerUserId`, `competenceStart`),
  KEY `billingEconomicFacts_type_competence_idx` (`factType`, `competenceStart`)
);

CREATE TABLE IF NOT EXISTS `billingEconomicMonthlyAggregates` (
  `aggregateKey` varchar(191) NOT NULL,
  `competenceMonth` date NOT NULL,
  `payerUserId` int NOT NULL,
  `subscriptionId` varchar(64) NULL,
  `productCode` varchar(120) NULL,
  `versionCode` varchar(191) NULL,
  `billingCycle` varchar(32) NULL,
  `currency` varchar(3) NOT NULL,
  `recognizedContractRevenueMinor` bigint NOT NULL DEFAULT 0,
  `discountMinor` bigint NOT NULL DEFAULT 0,
  `couponMinor` bigint NOT NULL DEFAULT 0,
  `creditMinor` bigint NOT NULL DEFAULT 0,
  `refundMinor` bigint NOT NULL DEFAULT 0,
  `chargebackMinor` bigint NOT NULL DEFAULT 0,
  `taxMinor` bigint NOT NULL DEFAULT 0,
  `receiptFeeMinor` bigint NOT NULL DEFAULT 0,
  `financialCostMinor` bigint NOT NULL DEFAULT 0,
  `netEconomicRevenueMinor` bigint NOT NULL DEFAULT 0,
  `variableCostMicros` bigint NOT NULL DEFAULT 0,
  `variableCostRatioBps` int NULL,
  `estimatedFactCount` bigint NOT NULL DEFAULT 0,
  `effectiveFactCount` bigint NOT NULL DEFAULT 0,
  `measurementCoverageBps` int NOT NULL DEFAULT 0,
  `ruleVersion` varchar(64) NOT NULL,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`aggregateKey`),
  KEY `billingEconomicMonthlyAggregates_month_idx` (`competenceMonth`),
  KEY `billingEconomicMonthlyAggregates_version_month_idx` (`versionCode`, `competenceMonth`)
);

CREATE TABLE IF NOT EXISTS `billingUsagePolicies` (
  `id` varchar(64) NOT NULL,
  `scopeType` varchar(32) NOT NULL,
  `scopeId` varchar(191) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `expectedBudgetMicros` bigint NOT NULL,
  `alertThresholdsJson` json NOT NULL,
  `observationStartsAt` timestamp NOT NULL,
  `observationEndsAt` timestamp NOT NULL,
  `activeScopeKey` varchar(191) NULL,
  `ruleVersion` varchar(64) NOT NULL,
  `createdByUserId` int NOT NULL,
  `reason` varchar(255) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `revokedAt` timestamp NULL,
  `revokedByUserId` int NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billingUsagePolicies_active_scope_uq` (`activeScopeKey`),
  KEY `billingUsagePolicies_scope_idx` (`scopeType`, `scopeId`)
);

CREATE TABLE IF NOT EXISTS `billingUsageAllowanceGrants` (
  `id` varchar(64) NOT NULL,
  `subjectType` varchar(32) NOT NULL,
  `subjectId` varchar(191) NOT NULL,
  `grantType` varchar(32) NOT NULL,
  `additionalUnits` bigint NULL,
  `reason` varchar(255) NOT NULL,
  `startsAt` timestamp NOT NULL,
  `endsAt` timestamp NOT NULL,
  `state` varchar(24) NOT NULL DEFAULT 'active',
  `createdByUserId` int NOT NULL,
  `revokedByUserId` int NULL,
  `revokedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `billingUsageAllowanceGrants_subject_state_idx` (`subjectType`, `subjectId`, `state`, `endsAt`)
);

CREATE TABLE IF NOT EXISTS `billingUsageAbuseCases` (
  `id` varchar(64) NOT NULL,
  `subjectUserId` int NOT NULL,
  `sponsorUserId` int NULL,
  `state` varchar(32) NOT NULL DEFAULT 'open',
  `signalsJson` json NOT NULL,
  `sanitizedEvidenceJson` json NOT NULL,
  `systemFailuresExcluded` boolean NOT NULL DEFAULT false,
  `legitimateGrowthReviewed` boolean NOT NULL DEFAULT false,
  `impactJson` json NULL,
  `openedByUserId` int NOT NULL,
  `reviewedByUserId` int NULL,
  `reviewOutcome` varchar(64) NULL,
  `reviewReason` varchar(255) NULL,
  `appealStatus` varchar(32) NULL,
  `appealResolution` varchar(255) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewedAt` timestamp NULL,
  `closedAt` timestamp NULL,
  PRIMARY KEY (`id`),
  KEY `billingUsageAbuseCases_subject_state_idx` (`subjectUserId`, `state`, `createdAt`)
);

CREATE TABLE IF NOT EXISTS `billingUsageLimitations` (
  `id` varchar(64) NOT NULL,
  `abuseCaseId` varchar(64) NOT NULL,
  `subjectUserId` int NOT NULL,
  `operationsJson` json NOT NULL,
  `reason` varchar(255) NOT NULL,
  `startsAt` timestamp NOT NULL,
  `endsAt` timestamp NOT NULL,
  `emergencySecurity` boolean NOT NULL DEFAULT false,
  `approvedByUserId` int NOT NULL,
  `secondApprovedByUserId` int NULL,
  `communicatedAt` timestamp NULL,
  `appealOfferedAt` timestamp NULL,
  `state` varchar(24) NOT NULL DEFAULT 'active',
  `revokedAt` timestamp NULL,
  `revokedByUserId` int NULL,
  `revokeReason` varchar(255) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `billingUsageLimitations_subject_state_idx` (`subjectUserId`, `state`, `endsAt`),
  KEY `billingUsageLimitations_case_idx` (`abuseCaseId`)
);

CREATE TABLE IF NOT EXISTS `billingConsumptionChargeAuthorizations` (
  `id` varchar(64) NOT NULL,
  `state` varchar(24) NOT NULL DEFAULT 'approved',
  `policyVersion` varchar(64) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `pricingJson` json NOT NULL,
  `affectedPlansJson` json NOT NULL,
  `effectiveFrom` timestamp NOT NULL,
  `communicationAt` timestamp NOT NULL,
  `noRetroactive` boolean NOT NULL DEFAULT true,
  `rollbackJson` json NOT NULL,
  `authorizedByUserId` int NOT NULL,
  `revokedByUserId` int NULL,
  `revokedAt` timestamp NULL,
  `revokeReason` varchar(255) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `billingConsumptionChargeAuthorizations_state_effective_idx` (`state`, `effectiveFrom`)
);

CREATE TABLE IF NOT EXISTS `billingUsageLegalHolds` (
  `id` varchar(64) NOT NULL,
  `scopeType` varchar(32) NOT NULL,
  `scopeId` varchar(191) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `startsAt` timestamp NOT NULL,
  `endsAt` timestamp NULL,
  `activeScopeKey` varchar(191) NULL,
  `createdByUserId` int NOT NULL,
  `revokedByUserId` int NULL,
  `revokedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billingUsageLegalHolds_active_scope_uq` (`activeScopeKey`),
  KEY `billingUsageLegalHolds_scope_idx` (`scopeType`, `scopeId`)
);

CREATE TABLE IF NOT EXISTS `billingUsageRetentionAudit` (
  `id` varchar(64) NOT NULL,
  `runAt` timestamp NOT NULL,
  `detailedCutoff` timestamp NOT NULL,
  `dailyCutoff` date NOT NULL,
  `monthlyCutoff` date NOT NULL,
  `ruleVersion` varchar(64) NOT NULL,
  `status` varchar(24) NOT NULL,
  `detail` varchar(255) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `billingUsageRetentionAudit_run_idx` (`runAt`)
);
