export type CatalogFoodReference = {
  slug: string;
  name: string;
  aliases: string[];
  servingLabel: string;
  gramsPerServing: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  isFruit?: boolean;
  isVegetable?: boolean;
  isUltraProcessed?: boolean;
  brandName?: string | null;
  variants?: string[];
  isBrandedProduct?: boolean;
};

export const FOOD_CATALOG_REFERENCE: CatalogFoodReference[] = [
  {
    slug: "cafe-sem-acucar",
    name: "Café sem açúcar",
    aliases: [
      "cafe sem acucar",
      "café sem açúcar",
      "cafe sem adicao de acucar",
      "café sem adição de açúcar",
      "cafe puro",
      "café puro",
      "cafe preto",
      "café preto",
      "cafe natural",
      "café natural",
    ],
    servingLabel: "1 xícara",
    gramsPerServing: 200,
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    variants: ["sem acucar", "sem açúcar", "sem adicao de acucar", "sem adição de açúcar", "puro", "preto", "natural"],
  },
  {
    slug: "cha-sem-acucar",
    name: "Chá sem açúcar",
    aliases: [
      "cha sem acucar",
      "chá sem açúcar",
      "cha sem adicao de acucar",
      "chá sem adição de açúcar",
      "cha puro",
      "chá puro",
      "cha natural",
      "chá natural",
    ],
    servingLabel: "1 xícara",
    gramsPerServing: 200,
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    variants: ["sem acucar", "sem açúcar", "sem adicao de acucar", "sem adição de açúcar", "puro", "natural"],
  },
  {
    slug: "agua",
    name: "Água",
    aliases: ["agua", "água", "agua natural", "água natural", "agua sem gas", "água sem gás"],
    servingLabel: "1 copo",
    gramsPerServing: 200,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    variants: ["natural", "sem gas", "sem gás"],
  },
  {
    slug: "agua-com-gas",
    name: "Água com gás",
    aliases: ["agua com gas", "água com gás", "agua gaseificada", "água gaseificada"],
    servingLabel: "1 copo",
    gramsPerServing: 200,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    variants: ["com gas", "com gás", "gaseificada"],
  },
  {
    slug: "iogurte-natural-nestle",
    name: "Iogurte natural Nestlé",
    aliases: [
      "iogurte natural nestle",
      "iogurte nestle natural",
      "nestle iogurte natural",
      "iogurte natural nestlé",
      "iogurte nestlé natural",
      "nestlé iogurte natural",
    ],
    servingLabel: "170 g",
    gramsPerServing: 170,
    calories: 108,
    protein: 6.0,
    carbs: 9.0,
    fat: 5.4,
    fiber: 0,
    brandName: "Nestlé",
    variants: ["natural"],
    isBrandedProduct: true,
  },
  {
    slug: "pao-integral-wickbold",
    name: "Pão integral Wickbold",
    aliases: [
      "pao integral wickbold",
      "pão integral wickbold",
      "wickbold pao integral",
      "wickbold pão integral",
    ],
    servingLabel: "2 fatias",
    gramsPerServing: 50,
    calories: 124,
    protein: 5.0,
    carbs: 21.0,
    fat: 2.0,
    fiber: 4.2,
    brandName: "Wickbold",
    variants: ["integral"],
    isUltraProcessed: true,
    isBrandedProduct: true,
  },
  {
    slug: "coca-cola-zero-lata",
    name: "Coca-Cola zero lata",
    aliases: [
      "coca zero lata",
      "coca-cola zero lata",
      "coca cola zero lata",
      "coca zero",
      "coca-cola zero",
      "coca cola zero",
    ],
    servingLabel: "1 lata",
    gramsPerServing: 350,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    brandName: "Coca-Cola",
    variants: ["zero", "sem acucar", "sem açúcar"],
    isUltraProcessed: true,
    isBrandedProduct: true,
  },
  {
    slug: "leite-molico-desnatado",
    name: "Leite Molico desnatado",
    aliases: [
      "leite molico",
      "leite molico desnatado",
      "molico leite",
      "molico desnatado",
    ],
    servingLabel: "200 ml",
    gramsPerServing: 200,
    calories: 70,
    protein: 6.8,
    carbs: 10.0,
    fat: 0,
    fiber: 0,
    brandName: "Molico",
    variants: ["desnatado"],
    isBrandedProduct: true,
  },
  {
    slug: "queijo-polenghi-light-fatia",
    name: "Queijo Polenghi light",
    aliases: [
      "queijo polenghi light",
      "polenghi light",
      "queijo light polenghi",
      "fatia queijo polenghi light",
      "fatias queijo polenghi light",
    ],
    servingLabel: "1 fatia",
    gramsPerServing: 20,
    calories: 44,
    protein: 3.6,
    carbs: 1.2,
    fat: 2.8,
    fiber: 0,
    brandName: "Polenghi",
    variants: ["light"],
    isUltraProcessed: true,
    isBrandedProduct: true,
  },
  {
    slug: "arroz-branco",
    name: "Arroz branco cozido",
    aliases: ["arroz", "arroz branco"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 130,
    protein: 2.7,
    carbs: 28.0,
    fat: 0.3,
    fiber: 0.4,
  },
  {
    slug: "feijao-carioca",
    name: "Feijão carioca cozido",
    aliases: ["feijao", "feijão", "feijão carioca"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 76,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.5,
    fiber: 8.5,
  },
  {
    slug: "frango-grelhado",
    name: "Frango grelhado",
    aliases: ["frango", "peito de frango", "frango grelhado"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    slug: "ovo",
    name: "Ovo de galinha",
    aliases: ["ovo", "ovos", "ovo cozido", "ovo mexido"],
    servingLabel: "1 unidade",
    gramsPerServing: 50,
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
  },
  {
    slug: "banana",
    name: "Banana",
    aliases: ["banana", "banana prata", "banana nanica"],
    servingLabel: "1 unidade",
    gramsPerServing: 80,
    calories: 72,
    protein: 0.9,
    carbs: 18.6,
    fat: 0.2,
    fiber: 2.1,
    isFruit: true,
  },
  {
    slug: "aveia",
    name: "Aveia em flocos",
    aliases: ["aveia", "aveia em flocos"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 117,
    protein: 4.2,
    carbs: 19.9,
    fat: 2.5,
    fiber: 2.7,
  },
  {
    slug: "pao-frances",
    name: "Pão francês",
    aliases: ["pao", "pão", "pão francês", "pao frances"],
    servingLabel: "1 unidade",
    gramsPerServing: 50,
    calories: 135,
    protein: 4.5,
    carbs: 28.0,
    fat: 1.5,
    fiber: 1.2,
  },
  {
    slug: "bisnaguinha-panco",
    name: "Bisnaguinha Panco",
    aliases: [
      "bisnaguinha",
      "bisnaguinhas",
      "bisnaguinha panco",
      "bisnaguinhas panco",
      "panco bisnaguinha",
      "panco bisnaguinhas",
      "pao bisnaguinha",
      "pão bisnaguinha",
      "paozinho panco",
      "pãozinho panco",
    ],
    servingLabel: "1 unidade",
    gramsPerServing: 20,
    calories: 62,
    protein: 1.8,
    carbs: 12.0,
    fat: 0.9,
    fiber: 0.6,
    brandName: "Panco",
    isUltraProcessed: true,
    isBrandedProduct: true,
  },
  {
    slug: "queijo-minas",
    name: "Queijo minas frescal",
    aliases: ["queijo minas", "queijo", "minas frescal"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 79,
    protein: 5.2,
    carbs: 1.0,
    fat: 6.2,
    fiber: 0,
  },
  {
    slug: "iogurte-natural",
    name: "Iogurte natural integral",
    aliases: ["iogurte", "iogurte natural"],
    servingLabel: "170 g",
    gramsPerServing: 170,
    calories: 104,
    protein: 5.9,
    carbs: 7.8,
    fat: 5.5,
    fiber: 0,
  },
  {
    slug: "batata-doce",
    name: "Batata doce cozida",
    aliases: ["batata doce", "batata-doce"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
    fiber: 2.2,
    isVegetable: true,
  },
  {
    slug: "salmao",
    name: "Salmão grelhado",
    aliases: ["salmao", "salmão", "salmão grelhado"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
    fiber: 0,
  },
  {
    slug: "salada-verde",
    name: "Salada verde",
    aliases: ["salada", "salada verde", "folhas"],
    servingLabel: "80 g",
    gramsPerServing: 80,
    calories: 18,
    protein: 1.2,
    carbs: 3.2,
    fat: 0.2,
    fiber: 1.6,
    isVegetable: true,
  },
  {
    slug: "maca",
    name: "Maçã",
    aliases: ["maca", "maçã"],
    servingLabel: "1 unidade",
    gramsPerServing: 130,
    calories: 68,
    protein: 0.3,
    carbs: 18.0,
    fat: 0.2,
    fiber: 3.0,
    isFruit: true,
  },
  {
    slug: "whey-protein",
    name: "Whey protein",
    aliases: ["whey", "whey protein", "proteína em pó"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 2.0,
    fiber: 0,
    isUltraProcessed: true,
  },
  {
    slug: "leite-integral",
    name: "Leite integral",
    aliases: ["leite", "leite integral"],
    servingLabel: "200 ml",
    gramsPerServing: 200,
    calories: 122,
    protein: 6.3,
    carbs: 9.4,
    fat: 6.6,
    fiber: 0,
  },
];
