export type CatalogFoodReference = {
  slug: string;
  name: string;
  aliases: string[];
  servingLabel: string;
  gramsPerServing: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export const FOOD_CATALOG_REFERENCE: CatalogFoodReference[] = [
  {
    slug: "arroz-branco",
    name: "Arroz branco cozido",
    aliases: ["arroz", "arroz branco"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 130,
    protein: 2.7,
    carbs: 28.0,
    fat: 0.3,
  },
  {
    slug: "feijao-carioca",
    name: "Feijão carioca cozido",
    aliases: ["feijao", "feijão", "feijão carioca"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 76,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.5,
  },
  {
    slug: "frango-grelhado",
    name: "Frango grelhado",
    aliases: ["frango", "peito de frango", "frango grelhado"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
  },
  {
    slug: "ovo",
    name: "Ovo de galinha",
    aliases: ["ovo", "ovos", "ovo cozido", "ovo mexido"],
    servingLabel: "1 unidade",
    gramsPerServing: 50,
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
  },
  {
    slug: "banana",
    name: "Banana",
    aliases: ["banana", "banana prata", "banana nanica"],
    servingLabel: "1 unidade",
    gramsPerServing: 80,
    calories: 72,
    protein: 0.9,
    carbs: 18.6,
    fat: 0.2,
  },
  {
    slug: "aveia",
    name: "Aveia em flocos",
    aliases: ["aveia", "aveia em flocos"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 117,
    protein: 4.2,
    carbs: 19.9,
    fat: 2.5,
  },
  {
    slug: "pao-frances",
    name: "Pão francês",
    aliases: ["pao", "pão", "pão francês", "pao frances"],
    servingLabel: "1 unidade",
    gramsPerServing: 50,
    calories: 135,
    protein: 4.5,
    carbs: 28.0,
    fat: 1.5,
  },
  {
    slug: "queijo-minas",
    name: "Queijo minas frescal",
    aliases: ["queijo minas", "queijo", "minas frescal"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 79,
    protein: 5.2,
    carbs: 1.0,
    fat: 6.2,
  },
  {
    slug: "iogurte-natural",
    name: "Iogurte natural integral",
    aliases: ["iogurte", "iogurte natural"],
    servingLabel: "170 g",
    gramsPerServing: 170,
    calories: 104,
    protein: 5.9,
    carbs: 7.8,
    fat: 5.5,
  },
  {
    slug: "batata-doce",
    name: "Batata doce cozida",
    aliases: ["batata doce", "batata-doce"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
  },
  {
    slug: "salmao",
    name: "Salmão grelhado",
    aliases: ["salmao", "salmão", "salmão grelhado"],
    servingLabel: "100 g",
    gramsPerServing: 100,
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
  },
  {
    slug: "salada-verde",
    name: "Salada verde",
    aliases: ["salada", "salada verde", "folhas"],
    servingLabel: "80 g",
    gramsPerServing: 80,
    calories: 18,
    protein: 1.2,
    carbs: 3.2,
    fat: 0.2,
  },
  {
    slug: "maca",
    name: "Maçã",
    aliases: ["maca", "maçã"],
    servingLabel: "1 unidade",
    gramsPerServing: 130,
    calories: 68,
    protein: 0.3,
    carbs: 18.0,
    fat: 0.2,
  },
  {
    slug: "whey-protein",
    name: "Whey protein",
    aliases: ["whey", "whey protein", "proteína em pó"],
    servingLabel: "30 g",
    gramsPerServing: 30,
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 2.0,
  },
  {
    slug: "leite-integral",
    name: "Leite integral",
    aliases: ["leite", "leite integral"],
    servingLabel: "200 ml",
    gramsPerServing: 200,
    calories: 122,
    protein: 6.3,
    carbs: 9.4,
    fat: 6.6,
  },
];
